### ISSUE TITLE
Search often fails

### ISSUE THREAD

**Issue by venil7** [xemwebe/yahoo_finance_api#10]
for example search term `TSLA`,`MSFT`, `AAPL` `bitcoin`
fails with error `deserializing response from yahoo! finance failed: missing field "longname"`

**Comment by xemwebe** [comment]
Have you observerd any other fields that are sometimes missing? 
There are typically two solutions to this problem: change the field to Option<String> or return an empty string if the field is missing the response. The first solution is more clean, but would mean a change on interface. Before I would go this path, I would like to be pretty sure that this problem does not occur with other fields, too (which would mean frequent interface changes).

**Comment by venil7** [comment]
It does happen for other fields too!
My preference would be `""`  as it doesnt change the interface

**Comment by venil7** [comment]
It also seems random 
for examlpe i get failure
`deserializing response from yahoo! finance failed: missing field "shortname"`
for search term `abc`, while previously it was returning values

I guess Y! finace api itself is not guaranteeing all fields at all times, hence best to fallback to `""`

**Comment by xemwebe** [comment]
I have implemented now both version, keeping the existing interface, but returning empty string for shortname and longname, if they missing, add added a new method (named with "_opt" at the end) that returns an Option for shortname and longname.

**Comment by venil7** [comment]
Awesome, thanks, version `1.1.4-dev` is not on crates.io yet, is it?

**Comment by xemwebe** [comment]
Not yet, I wanted to update the docs and make sure that it does work before I publish an update to crates.io, will do so soon.

**Comment by xemwebe** [comment]
It's now pushed to crates.io, closing issue
