### ISSUE TITLE
missing field 'adjclose'

### ISSUE THREAD

**Issue by thinkrapido** [xemwebe/yahoo_finance_api#20]
```rust
yahoo::YahooConnector::new().get_quote_history_interval(...).await?.quotes()?
```

```rust
Error: deserializing response from yahoo! finance failed

Caused by:
    missing field `adjclose`
```

**Comment by thinkrapido** [comment]
![image](https://user-images.githubusercontent.com/1568087/195918404-9740762d-e575-4303-9d47-5d96c35d4fe4.png)

**Comment by xemwebe** [comment]
@thinkrapido : What do you want to tell me with this post?

**Comment by xemwebe** [comment]
If yahoo does not provide this field, the library can't either.
