### ISSUE TITLE
no method named `timeout` found for struct `ClientBuilder` in the current scope

### ISSUE THREAD

**Issue by paras301** [xemwebe/yahoo_finance_api#25]
Cargo build is failing - 

>    Compiling yahoo_finance_api v1.4.0
> error[E0599]: no method named `timeout` found for struct `ClientBuilder` in the current scope
>    --> C:\Users\email\.cargo\registry\src\github.com-1ecc6299db9ec823\yahoo_finance_api-1.4.0\src\lib.rs:247:33
>     |
> 247 |         self.inner = self.inner.timeout(timeout);
>     |                                 ^^^^^^^ method not found in `ClientBuilder`
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `yahoo_finance_api` due to previous error
> Error: Compiling your crate to WebAssembly failed
> Caused by: failed to execute `cargo build`: exited with exit code: 101

**Comment by xemwebe** [comment]
I can't reproduce this error. 
How did you try to t build the project? Did you try to compile to WebAssembly? This is not supported (yet).

**Comment by paras301** [comment]
Yes my bad. I forgot to mention it. I tried to compile for WebAssembly only. Any idea when will it be support or any alternatives you can suggest me?
