### ISSUE TITLE
API grammar suggests multiple ticker request/response 

### ISSUE THREAD

**Issue by gurpal2000** [xemwebe/yahoo_finance_api#30]
Thank you for creating this API.

Just one thing. The connector has a function get_latest_quotes() ie. Plural.

Yet I only see support for a single ticker. Wouldn't the call be better as get_latest_quote() ie. singular

Incidentally are people using loops with a minute delay or so?

**Comment by xemwebe** [comment]
The plural is intentional. The function returns multiple quotes for a single ticker, e.g. all quotes of the most recent day or week. This justifies the plural.
