### ISSUE TITLE
Re-export dependencies?

### ISSUE THREAD

**Issue by andber1** [xemwebe/yahoo_finance_api#31]
Should the time crate be re-exported (as described [here](https://lurklurk.org/effective-rust/re-export.html))? In order to use the function `get_quote_history`, e.g., I have to add the time crate on myself (because I need the OffsetDateTime struct or datetime macro). But it would be nice not to have to worry about that (not to mention finding the correct version in case of breaking changes in the time crate) and just write `use yahoo_finance_api::export::time`, or something similar.

**Comment by xemwebe** [comment]
Yes, that's a good idea. Thank your for the suggestion. I have just pushed & published this small change.
