### ISSUE TITLE
thoughts on using [request](https://crates.io/crates/reqwest)

### ISSUE THREAD

**Issue by 0xJepsen** [xemwebe/yahoo_finance_api#37]
would you be open to using the [request](https://crates.io/crates/reqwest) crate to allow for the http library to not bubble everything up to be async?

then you can do things like
```rust
        let resp = reqwest::blocking::get(url);
```

**Comment by xemwebe** [comment]
I am not sure, if I understand correctly what you are suggesting... if you use the blocking feature, you cN already avoid the use of async in your code.

**Comment by 0xJepsen** [comment]
Let me try to explain a little better. Right now if i use this API, the `async` propagates up which makes everything that calls it async. Some people have called this a "red function" as described [here](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/).  If instead on the send here
https://github.com/xemwebe/yahoo_finance_api/blob/7652601c6dc079cdc685348a5ff0cb56303d094f/src/async_impl.rs#L80-L87
you used the `request` crate your function can be blue and not propagate the `async`
> then you can do things like
> 
> ```rust
>         let resp = reqwest::blocking::get(url);
> ```

Would you be open to this change? If so I would maybe be interested in working on it

**Comment by 0xJepsen** [comment]
After taking a closer look, i see you already support this with the blocking feature! Amazing
