### ISSUE TITLE
How to retrieve previous day closing value

### ISSUE THREAD

**Issue by carlocaione** [xemwebe/yahoo_finance_api#39]
I'm probably missing something but I'm failing to understand how to retrieve the previous close value as in the picture.

The `YMetaData::previous_close` is always `None` while the `YMetaData:: chart_previous_close` is way off the real value.

<img width="692" alt="Screenshot 2024-03-02 at 16 09 40" src="https://github.com/xemwebe/yahoo_finance_api/assets/357758/036dfcfc-8915-4ce3-a4bc-887d639777c8">

**Comment by xemwebe** [comment]
Could u provide an example ticker where you observe this problem, so that I could reproduce the result?

**Comment by carlocaione** [comment]
> Could u provide an example ticker where you observe this problem, so that I could reproduce the result?

For example `VWCE.MI`.

**Comment by xemwebe** [comment]
The API seems to return a value. Unfortunately, I can't debug this currently, since I get always a "429 Too Many Requests". Personally, I have definitely not exhausted the 2000 request per hour or so that seems to be allowed by yahoo!. I still can access the API via browser, so it's not the IP address that is blocked.

**Comment by xemwebe** [comment]
Apparently, the yahoo! API does not always provides a value for `previous_close`. Sometimes it's there, sometimes not and I am not sure what triggers this. That's the basic reason why this field is optional, and there's nothing I can do about this.

However, the field `chart_previous_close` is always present and has the same value as `previous_close` (if the latter is provided) in all cases I have analyzed so far. So maybe you could use this value instead.
