### ISSUE TITLE
`Quote` implementing `Serialize` (and `Deserialize`)?

### ISSUE THREAD

**Issue by meuter** [xemwebe/yahoo_finance_api#40]
Hi, 

Would you be open to add `Serialize` and `Deserialize` to the list of derived traits on `Quote` here:

https://github.com/xemwebe/yahoo_finance_api/blob/c967fc8b848f183858feff2cd4c2870724237e67/src/quotes.rs#L127

If so, I would be happy to submit a PR for that.

Thanks in advance for considering this.

EDIT: might as well add `Deserialize` ;-)

-Cédric

**Comment by xemwebe** [comment]
Adding Serialize and Deserialize is fine, please feel invited to prepare a PR.

**Comment by meuter** [comment]
Thanks! PR is submited.
