### ISSUE TITLE
429: Too Many Requests

### ISSUE THREAD

**Issue by austinjp17** [xemwebe/yahoo_finance_api#42]
I've been testing for about a week now, out of laziness I fetched every run and didn't locally save any data. I started receiving 429 responses to any fetch request two days ago. I find it very hard to believe I've hit that yahoo's daily limit of 8000. Now that it's been two days I'm not seeing any rate limit I would be subjected to. 

Additionally, it could be useful providing access to the reqwest client build. I was thinking Yahoo may like me a little more if I gave a user agent but the client is forced to default.

Is there something I'm missing causing me to get persistent 429s?

**Comment by xemwebe** [comment]
The issue is solved with version 2.2.0 (just published)
